#!/usr/bin/env python3
"""Robustness and dispersion numbers, for the section the reviewers asked for.

Three separate rejections of thermal work from this author named the same gap:
no multi-run statistics, no baseline comparison, no sensitivity analysis on the
calibration. All three are answerable from the September campaign without
touching the board again. This script emits the macros for them.

Outputs paper/numbers_robust.tex, \\input alongside numbers_v3.tex.
"""
import csv
import glob
import json
import os
import re
import statistics as st
import collections

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RES = json.load(open(os.path.join(HERE, "data", "all_results2.json")))
CAL = json.load(open(os.path.join(HERE, "data", "calib.json")))
OUT = os.path.join(HERE, "paper", "numbers_robust.tex")

lines = ["% generated by scripts/fill_robustness.py -- do not edit"]


def put(name, val):
    lines.append(r"\newcommand{\np%s}{%s}" % (name, val))


# ---------------------------------------------------------------- dispersion
cells = collections.defaultdict(list)
for k, v in RES.items():
    c = v["config"]
    cells[(c["mix"], c["arrival"], c["load"], c["mode"], c.get("t_cap"))].append(v)


def cell(load, pol, cap=54.0):
    return cells.get(("hetero", "poisson", load, pol, cap), [])


def ms(vals, prec=2):
    """mean +/- sample SD, or the single value."""
    if len(vals) < 2:
        return "%.*f" % (prec, vals[0]) if vals else "n/a"
    return "%.*f$\\,\\pm\\,$%.*f" % (prec, st.mean(vals), prec, st.stdev(vals))


def secs(vals):
    v = [x / 1000.0 for x in vals]
    if len(v) < 2:
        return "%.1f" % v[0] if v else "n/a"
    return "%.1f$\\,\\pm\\,$%.1f" % (st.mean(v), st.stdev(v))


rows = []
for load, label in (("low", "low"), ("high", "high"), ("extreme", "extreme")):
    first = True
    for pol in ("equal", "convex", "matched", "admission"):
        v = cell(load, pol)
        if not v:
            continue
        rows.append("%s & %s & %d & %s & %s & %s \\\\" % (
            label if first else "", pol, len(v),
            ms([x["goodput_tight"] for x in v]),
            secs([x["p99_worst_ms"] for x in v]),
            ms([x["controller"]["T_max"] for x in v], 1)))
        first = False
    rows.append(r"\addlinespace[1pt]")
put("TableDispersion", "%\n" + "\n".join(rows).rstrip("\\addlinespace[1pt]").rstrip() + "}"[:0])

# The claim the dispersion is there to support: at low load every policy is
# within noise of every other, and at high/extreme the three capped policies
# are within noise of each other while equal sharing is separated.
lo = {p: [x["goodput_tight"] for x in cell("low", p)]
      for p in ("equal", "convex", "matched", "admission")}
lo_all = [x for v in lo.values() for x in v]
put("LowSpreadPct", "%.1f" % (100 * (max(lo_all) - min(lo_all)) / st.mean(lo_all)))
put("LowSDMax", "%.2f" % max(st.stdev(v) for v in lo.values()))

hi_cap = {p: [x["p99_worst_ms"] / 1000 for x in cell("high", p)]
          for p in ("convex", "matched", "admission")}
put("HighPnnConvex", "%.0f$\\,\\pm\\,$%.0f" % (
    st.mean(hi_cap["convex"]), st.stdev(hi_cap["convex"])))
put("HighPnnMatched", "%.0f$\\,\\pm\\,$%.0f" % (
    st.mean(hi_cap["matched"]), st.stdev(hi_cap["matched"])))
put("HighPnnAdmission", "%.0f$\\,\\pm\\,$%.0f" % (
    st.mean(hi_cap["admission"]), st.stdev(hi_cap["admission"])))
hi_eq = [x["p99_worst_ms"] / 1000 for x in cell("high", "equal")]
put("HighPnnEqual", "%.1f$\\,\\pm\\,$%.1f" % (st.mean(hi_eq), st.stdev(hi_eq)))
put("HighGpEqual", "%.2f$\\,\\pm\\,$%.2f" % (
    st.mean([x["goodput_tight"] for x in cell("high", "equal")]),
    st.stdev([x["goodput_tight"] for x in cell("high", "equal")])))

# The medium-load SD is the evidence for bimodality, not noise to apologise for.
med_cx = [x["goodput_tight"] for x in cell("med", "convex")]
put("MedGpConvexMean", "%.1f" % st.mean(med_cx))
put("MedGpConvexSD", "%.1f" % st.stdev(med_cx))
med_eq = [x["goodput_tight"] for x in cell("med", "equal")]
put("MedGpEqualSD", "%.2f" % st.stdev(med_eq))

# ---------------------------------------------------------------- sensor step
vals = set()
for p in glob.glob(os.path.join(HERE, "data", "logs", "*", "controller.csv")):
    for r in csv.DictReader(open(p)):
        vals.add(float(r["T_c"]))
v = sorted(vals)
gaps = sorted({round(b - a, 4) for a, b in zip(v, v[1:])})
put("SensorStep", "%.2f" % gaps[0])

# ---------------------------------------------------------------- cap sweep
cap_rows = []
for cap, name in ((50.6, "tight"), (54.0, "primary"), (57.4, "loose")):
    for pol in ("convex", "admission"):
        if cap == 54.0:
            v = cell("med", pol)
        else:
            v = [x for k, x in RES.items()
                 if x["config"].get("t_cap") == cap and x["config"]["mode"] == pol
                 and x["config"]["load"] == "med"]
        if not v:
            continue
        cap_rows.append("%s (%.1f) & %s & %d & %s & %s & %s \\\\" % (
            name if pol == "convex" else "", cap, pol, len(v),
            ms([x["goodput_tight"] for x in v], 1),
            secs([x["p99_worst_ms"] for x in v]),
            ms([x["controller"]["agg_duty_mean"] for x in v])))
    cap_rows.append(r"\addlinespace[1pt]")
put("TableCapSweep", "%\n" + "\n".join(cap_rows))

# ---------------------------------------------------------- calibration drift
b0, k, k_old = CAL["idle_temp_c"], CAL["slope_c_per_pct"], CAL["slope_mar2026_c_per_pct"]
put("SlopeNew", "%.3f" % k)
put("SlopeOld", "%.3f" % k_old)
put("SlopeDriftPct", "%.1f" % abs(100 * (k - k_old) / k_old))
# Inverting T = b0 + kU at the cap: the budget error is exactly the slope error.
put("BudgetErrPct", "%.1f" % abs(100 * ((54.0 - b0) / k_old - (54.0 - b0) / k)
                                 / ((54.0 - b0) / k)))

moves = []
for p in sorted(glob.glob(os.path.join(HERE, "data", "logs",
                                       "hetero_poisson_*", "controller.csv"))):
    name = os.path.basename(os.path.dirname(p))
    if not re.search(r"_(convex|admission)_", name):
        continue
    r = list(csv.DictReader(open(p)))
    if len(r) < 60:
        continue
    seed = float(r[0]["agg_duty"])
    settled = st.mean(float(x["agg_duty"]) for x in r[-60:])
    moves.append(abs(100 * (settled - seed) / seed))
put("FeedbackMovePct", "%.0f" % st.mean(moves))
put("FeedbackMoveMin", "%.0f" % min(moves))
put("FeedbackMoveMax", "%.0f" % max(moves))
put("FeedbackVsDrift", "%.0f" % (st.mean(moves) / abs(100 * (k - k_old) / k_old)))
put("NFeedbackRuns", str(len(moves)))

open(OUT, "w", newline="\n").write("\n".join(lines) + "\n")
print("wrote", OUT, "(%d macros)" % (len(lines) - 1))
