#!/usr/bin/env python3
"""Macros for the sections the Letter had no room for.

The September campaign is 124 runs. The Letter's main table reports 52 of them
(heterogeneous mix, Poisson arrivals, primary cap) and compresses the other 72
into three sentences. Those 72 are not filler: the homogeneous mix is 48 runs
that independently reproduce the whole result, the bursty-arrival cells are a
clean null, and the closed-loop cells refute the original claim under the
original claim's own protocol, which is a stronger retraction than "we used the
wrong protocol".

Outputs paper/numbers_generality.tex.
"""
import collections
import json
import os
import statistics as st

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RES = json.load(open(os.path.join(HERE, "data", "all_results2.json")))
OUT = os.path.join(HERE, "paper", "numbers_generality.tex")

lines = ["% generated by scripts/fill_generality.py -- do not edit"]


def put(name, val):
    lines.append(r"\newcommand{\np%s}{%s}" % (name, val))


C = collections.defaultdict(list)
for k, v in RES.items():
    c = v["config"]
    C[(c["mix"], c["arrival"], c["load"], c["mode"], c.get("t_cap"))].append(v)


def ms(vals, prec=2):
    if not vals:
        return "n/a"
    if len(vals) < 2:
        return "%.*f" % (prec, vals[0])
    return "%.*f$\\,\\pm\\,$%.*f" % (prec, st.mean(vals), prec, st.stdev(vals))


def get(mix, arr, load, pol, cap=54.0):
    return C.get((mix, arr, load, pol, cap), [])


def gp(v):
    return [x["goodput_tight"] for x in v]


def p99(v):
    return [x["p99_worst_ms"] for x in v]


def tmax(v):
    return [x["controller"]["T_max"] for x in v]


def duty(v):
    return [x["controller"]["agg_duty_mean"] for x in v]


# ------------------------------------------------- homogeneous mix, 48 runs
rows = []
for load in ("low", "med", "high", "extreme"):
    first = True
    for pol in ("equal", "convex", "matched", "admission"):
        v = get("homo", "poisson", load, pol)
        if not v:
            continue
        rows.append("%s & %s & %d & %s & %s & %s & %s \\\\" % (
            load if first else "", pol, len(v),
            ms(gp(v), 1),
            ms([x / 1000.0 for x in p99(v)], 1),
            ms(tmax(v), 1),
            ms(duty(v))))
        first = False
    rows.append(r"\addlinespace[1pt]")
put("TableHomo", "%\n" + "\n".join(rows))

put("HomoLowSpread", "%.1f" % (
    100 * (max(max(gp(get("homo", "poisson", "low", p)))
               for p in ("equal", "convex", "matched", "admission"))
           - min(min(gp(get("homo", "poisson", "low", p)))
                 for p in ("equal", "convex", "matched", "admission")))
    / st.mean(gp(get("homo", "poisson", "low", "equal")))))
put("HomoMedEqual", ms(gp(get("homo", "poisson", "med", "equal")), 1))
put("HomoMedConvex", ms(gp(get("homo", "poisson", "med", "convex")), 1))
put("HomoMedMatched", ms(gp(get("homo", "poisson", "med", "matched")), 1))
put("HomoMedAdmission", ms(gp(get("homo", "poisson", "med", "admission")), 1))
put("HomoHighTmaxEqual", ms(tmax(get("homo", "poisson", "high", "equal")), 1))
put("HomoHighTmaxConvex", ms(tmax(get("homo", "poisson", "high", "convex")), 1))
put("HomoHighPnnEqual", ms([x / 1000 for x in p99(get("homo", "poisson", "high", "equal"))], 1))
put("HomoHighPnnConvex", ms([x / 1000 for x in p99(get("homo", "poisson", "high", "convex"))], 1))

# ------------------------------------------------- bursty on-off, 8 runs
b = {p: get("hetero", "onoff", "med", p) for p in
     ("equal", "convex", "matched", "admission")}
allgp = [x for p in b.values() for x in gp(p)]
put("BurstGpMin", "%.1f" % min(allgp))
put("BurstGpMax", "%.1f" % max(allgp))
put("BurstSpreadPct", "%.1f" % (100 * (max(allgp) - min(allgp)) / st.mean(allgp)))
put("BurstDuty", ms([x for p in b.values() for x in duty(p)]))
put("BurstPnn", ms([x / 1000 for x in
                    (p99(b["equal"]) + p99(b["convex"]))], 1))

# ------------------------------------------------- closed loop, 8 runs
# This is the retraction, measured under the protocol that produced the claim.
for mix in ("hetero", "homo"):
    e = get(mix, "saturate", "extreme", "equal")
    c = get(mix, "saturate", "extreme", "convex")
    tag = "Het" if mix == "hetero" else "Hom"
    put("Sat%sEqualPnn" % tag, ms(p99(e), 0))
    put("Sat%sConvexPnn" % tag, ms(p99(c), 0))
    put("Sat%sRatio" % tag, "%.2f" % (st.mean(p99(c)) / st.mean(p99(e))))
    put("Sat%sEqualTput" % tag, ms([x["throughput"] for x in e], 1))
    put("Sat%sConvexTput" % tag, ms([x["throughput"] for x in c], 1))
    put("Sat%sTputLoss" % tag, "%.0f" % (
        100 * (1 - st.mean([x["throughput"] for x in c])
               / st.mean([x["throughput"] for x in e]))))
    put("Sat%sTmaxEqual" % tag, ms(tmax(e), 1))
    put("Sat%sTmaxConvex" % tag, ms(tmax(c), 1))

# ------------------------------------------------- rate-curve proportionality
# The redundancy proof needs the measured curves to be proportional (zero
# intercept). Report how close they actually are rather than assuming it.
CAL = json.load(open(os.path.join(HERE, "data", "calib.json")))
worst_spread, worst_icept = 0.0, 0.0
for m, v in CAL["models"].items():
    pts = v["duty_curve"]
    sl = [y / x for x, y in pts]
    worst_spread = max(worst_spread,
                       100 * (max(sl) - min(sl)) / (sum(sl) / len(sl)))
    n = len(pts)
    sx = sum(x for x, _ in pts); sy = sum(y for _, y in pts)
    sxx = sum(x * x for x, _ in pts); sxy = sum(x * y for x, y in pts)
    aa = (n * sxy - sx * sy) / (n * sxx - sx * sx)
    bb = (sy - aa * sx) / n
    worst_icept = max(worst_icept, 100 * abs(bb) / aa)
put("CurveSpreadPct", "%.1f" % worst_spread)
put("CurveInterceptPct", "%.2f" % worst_icept)

put("NRunsTotal", str(len(RES)))
put("NRunsMain", str(sum(len(v) for (m, a, l, p, c), v in C.items()
                         if m == "hetero" and a == "poisson" and c == 54.0)))

open(OUT, "w", newline="\n").write("\n".join(lines) + "\n")
print("wrote", OUT, "(%d macros)" % (len(lines) - 1))
