#!/usr/bin/env python3
"""Energy per unit goodput: the one gap the September campaign could not fill.

IoT-J Reviewer 2 asked for energy per unit goodput. The September logs carry no
power column, so the number had to be measured. energy2.py re-ran a 28-run
subset with a 10 Hz PMIC rail sampler alongside each run, writing power.txt into
each run directory; this reduces those into the paper's macros.

Energy per SLA-met request = mean package power / goodput. Where goodput is zero
the ratio is undefined, and that is itself the finding rather than a gap: at
high and extreme load the capped policies draw power and deliver nothing.

Outputs paper/numbers_energy.tex.
"""
import csv
import glob
import json
import os
import statistics as st

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CAL = json.load(open(os.path.join(HERE, "data", "calib.json")))
OUT = os.path.join(HERE, "paper", "numbers_energy.tex")
SLA_FACTOR = 2.5          # tight SLA, same rule as analyze2.py
WARMUP_S = 20.0
DUR = 180.0

lines = ["% generated by scripts/fill_energy.py -- do not edit"]


def put(name, val):
    lines.append(r"\newcommand{\np%s}{%s}" % (name, val))


def goodput(d):
    """SLA-met requests per second, summed over tenants, as analyze2.py does."""
    span = DUR - WARMUP_S
    met = 0
    for f in glob.glob(os.path.join(d, "latency_t*_*.csv")):
        key = os.path.basename(f).split("_", 2)[2].rsplit(".", 1)[0]
        solo = CAL["models"].get(key, {}).get("solo_med_ms")
        if solo is None:
            continue
        sla = SLA_FACTOR * solo
        with open(f) as fh:
            for row in csv.DictReader(fh):
                if row.get("warmup") == "1":
                    continue
                if float(row["latency_ms"]) <= sla:
                    met += 1
    return met / span


runs = {}
for d in sorted(glob.glob(os.path.join(HERE, "data", "logs_energy", "*"))):
    cfgp = os.path.join(d, "config.json")
    pf = os.path.join(d, "power.txt")
    if not (os.path.exists(cfgp) and os.path.exists(pf)):
        continue
    w = [float(x) for x in open(pf) if x.strip()]
    if not w:
        continue
    cfg = json.load(open(cfgp))
    gp = goodput(d)
    runs.setdefault((cfg["load"], cfg["mode"]), []).append(
        {"W": st.mean(w), "gp": gp,
         "mJ_per_req": (st.mean(w) / gp * 1000) if gp > 0 else None})


def agg(load, mode, key):
    v = [r[key] for r in runs.get((load, mode), []) if r[key] is not None]
    return v


def ms(v, prec=2):
    if not v:
        return "n/a"
    if len(v) < 2:
        return "%.*f" % (prec, v[0])
    return "%.*f$\\,\\pm\\,$%.*f" % (prec, st.mean(v), prec, st.stdev(v))


rows = []
for load in ("low", "med", "high", "extreme"):
    first = True
    for mode in ("equal", "convex", "matched", "admission"):
        if (load, mode) not in runs:
            continue
        n = len(runs[(load, mode)])
        e = agg(load, mode, "mJ_per_req")
        rows.append("%s & %s & %d & %s & %s & %s \\\\" % (
            load if first else "", mode, n,
            ms(agg(load, mode, "W")),
            ms(agg(load, mode, "gp"), 1),
            ms(e, 0) if e else r"\emph{undefined}"))
        first = False
    rows.append(r"\addlinespace[1pt]")
put("TableEnergy", "%\n" + "\n".join(rows))

# The headline comparisons.
for load in ("low", "med"):
    for mode in ("equal", "convex", "matched", "admission"):
        e = agg(load, mode, "mJ_per_req")
        if e:
            put("E%s%s" % (load.capitalize(), mode.capitalize()), ms(e, 0))

# Power alone barely moves; it is goodput that moves. Quantify both.
allW = [r["W"] for v in runs.values() for r in v]
put("EWmin", "%.2f" % min(allW))
put("EWmax", "%.2f" % max(allW))
eq_hi = agg("high", "equal", "W")
cx_hi = agg("high", "convex", "W")
if eq_hi and cx_hi:
    put("EWhighEqual", ms(eq_hi))
    put("EWhighConvex", ms(cx_hi))
    put("EWhighSavePct", "%.0f" % (100 * (1 - st.mean(cx_hi) / st.mean(eq_hi))))
# The medium-load cell is bimodal, so a mean hides the result. Count instead.
capped_med = [r for m in ("convex", "matched", "admission")
              for r in runs.get(("med", m), [])]
zero = [r for r in capped_med if r["gp"] == 0]
deliv = [r for r in capped_med if r["gp"] > 0]
put("EMedCappedTotal", str(len(capped_med)))
put("EMedCappedZero", str(len(zero)))
put("EMedCappedDeliv", str(len(deliv)))
if zero:
    put("EMedZeroWmin", "%.1f" % min(r["W"] for r in zero))
    put("EMedZeroWmax", "%.1f" % max(r["W"] for r in zero))
if deliv:
    put("EMedDelivE", "%.0f" % st.mean([r["mJ_per_req"] for r in deliv]))
eq_med = runs.get(("med", "equal"), [])
if eq_med and deliv:
    put("EMedEqualE", "%.0f" % st.mean([r["mJ_per_req"] for r in eq_med]))
    put("EMedPremiumPct", "%.0f" % (
        100 * (st.mean([r["mJ_per_req"] for r in deliv])
               / st.mean([r["mJ_per_req"] for r in eq_med]) - 1)))
    put("EMedEqualW", "%.2f" % st.mean([r["W"] for r in eq_med]))
    put("EMedPowerSavePct", "%.0f" % (
        100 * (1 - st.mean([r["W"] for r in capped_med])
               / st.mean([r["W"] for r in eq_med]))))
lo = [r["mJ_per_req"] for m in ("equal", "convex", "matched", "admission")
      for r in runs.get(("low", m), []) if r["mJ_per_req"]]
put("ELowMin", "%.0f" % min(lo))
put("ELowMax", "%.0f" % max(lo))

put("ENRuns", str(sum(len(v) for v in runs.values())))
put("ESampleRate", "10")

open(OUT, "w", newline="\n").write("\n".join(lines) + "\n")
print("wrote", OUT, "(%d macros)" % (len(lines) - 1))
for k in sorted(runs):
    e = [r["mJ_per_req"] for r in runs[k] if r["mJ_per_req"]]
    print("  %-8s %-10s n=%d  W=%.2f  gp=%.1f  mJ/req=%s"
          % (k[0], k[1], len(runs[k]),
             st.mean([r["W"] for r in runs[k]]),
             st.mean([r["gp"] for r in runs[k]]),
             ("%.0f" % st.mean(e)) if e else "undefined (zero goodput)"))
